services:

  # ollama and API
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-api
    pull_policy: missing
    tty: true
    restart: unless-stopped
    # Expose Ollama API outside the container stack
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    # GPU support (turn off by commenting with # if you don't have an nvidia gpu)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
  # FastAPI server
  fastapi-server:
    build:
      context: .
      dockerfile: Dockerfile # Path to your FastAPI server file
    ports:
      - 8000:8000 # Expose the FastAPI port
    depends_on:
      - ollama # Ensure Ollama is up and running first

volumes:
  ollama: {}
